############################################################
##    FILENAME:   testData2libsvmData.py    
##    VERSION:    1.0
##    SINCE:      2014-04-07
##    AUTHOR: 
##        Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
##
############################################################
##    Edited by MacVim
##    Documentation auto-generated by Snippet 
############################################################

import csv
with open ('./PCA_test.csv') as inTest, \
        open('./libsvm_PCA_test.csv', 'wb+') as outTest:

    inTest = csv.reader(inTest, delimiter=',')
    outTest = csv.writer(outTest, delimiter=' ')

    for line in inTest:
        outline = [str(0)]
        for i in range(0, len(line)):
            outline.append(str(i+1)+':'+str(line[i]))
        outTest.writerows([outline])
        
