############################################################
##    FILENAME:   trainData2libsvmData.py    
##    VERSION:    1.0
##    SINCE:      2014-04-07
##    AUTHOR: 
##        Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
##
############################################################
##    Edited by MacVim
##    Documentation auto-generated by Snippet 
############################################################

import csv

with open ('./PCA_train.csv') as inTest, \
        open('./libsvm_PCA_train.csv', 'wb+') as outTest:

    inTest = csv.reader(inTest, delimiter=',')
    outTest = csv.writer(outTest, delimiter=' ')

    for line in inTest:
        outline = [str(line[0])]
        for i in range(1, len(line)):
            outline.append(str(i)+':'+str(line[i]))
        outTest.writerows([outline])
        
